package com.blackstone.device.notification

/**
 * @author Evgeny Butov
 * @created 17.08.2019
 */
object Const {
    const val NOTIFICATION_FORPOST_CLOSE = "NOTIFICATION_FORPOST_CLOSE"
    const val NOTIFICATION_OCTAL_CLOSE = "NOTIFICATION_OCTAL_CLOSE"
    const val NOTIFICATION_FORPOST_TP = "NOTIFICATION_FORPOST_TP"
    const val NOTIFICATION_OCTAL_TP = "NOTIFICATION_OCTAL_TP"

    const val NOTIFICATION_ID_FORPOST_CLOSE = 0
    const val NOTIFICATION_ID_OCTAL_CLOSE = 1
    const val NOTIFICATION_ID_FORPOST_TP = 2
    const val NOTIFICATION_ID_OCTAL_TP = 3

    const val NOTIFICATION_CHANNEL = "NLR_NOTIFICATION"
}